env:
  - DOCKER_REGISTRY={{ if index .Env "DOCKER_REGISTRY"  }}{{ .Env.DOCKER_REGISTRY }}{{ else }}localrepo{{ end }}
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    main: ./cmd/steward/main.go
    binary: steward
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  - use: buildx
    dockerfile: Dockerfile_release
    goos: linux
    goarch: amd64
    image_templates:
      - "{{ .Env.DOCKER_REGISTRY }}/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "{{ .Env.DOCKER_REGISTRY }}/{{ .ProjectName }}:latest"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
brews:
  -
    name: steward
    homepage: "https://github.com/RaaLabs/steward"
    # The GitHub repository to push the forula to
    tap:
      owner: raalabs
      name: homebrew-raalabs
      branch: main
      token: {{ secrets.RAALABS_BREW_TAP_TOKEN_STEWARD }}
